export const popular = [
  {
    id: 1,
    image: "https://mcdonalds.bg/wp-content/uploads/2023/02/bigmac_500h500.png",
    name: "Big Mac",
    price: "3.39",
    dis: "Sesame bun with two 100% beef patties and special Big MacTM sauce, fresh lettuce, Cheddar cheese (51%), pickle slices and onions.",
    type: "Burgers & Sandwiches",
    starts: 4.7,
  },
  {
    id: 2,
    image:
      "https://mcdonalds.bg/wp-content/uploads/2023/11/mac-toast-cheddar-website_500x500.png",
    name: "McToast™",
    price: "2.39",
    dis: "Warm bread, ham, Cheddar cheese (51%).",
    type: "Burgers & Sandwiches",
    starts: 4.6,
  },
  {
    id: 3,
    image:
      "https://mcdonalds.bg/wp-content/uploads/2023/11/deli-burger_500x500.png",
    name: "Deli burger",
    price: "1.56",
    dis: "Warm bun, beef, pickles and Caesar sauce (The product is available only with McDonald's App)",
    type: "Burgers & Sandwiches",
    starts: 4.8,
  },
  {
    id: 4,
    image:
      "https://mcdonalds.bg/wp-content/uploads/2024/05/caesar-chicken-1.png",
    name: "Ceaser Beef",
    price: "3.79",
    dis: "Golden sesame bun with poppy seed, special Ceaser sauce, fresh tomatoes and red onion, arugula salad, Emmental cheese (15%) and juicy 100% beef!",
    type: "Burgers & Sandwiches",
    starts: 4.9,
  },
  {
    id: 5,
    image:
      "https://mcdonalds.bg/wp-content/uploads/2023/11/cheese-burger_500x500.png",
    name: "Cheeseburger",
    price: "2.30",
    dis: "Warm bun, 100% beef, Cheddar cheese, ketchup, mustard, pickles, onion.",
    type: "Burgers & Sandwiches",
    starts: 4.5,
  },
  {
    id: 6,
    image:
      "https://mcdonalds.bg/wp-content/uploads/2023/11/mcchicken_500x500.png",
    name: "Crispy Chicken",
    price: "2.39",
    dis: "Delicious golden chicken in a warm, freshly baked bun with sesame and poppy seeds, fresh tomatoes, fresh arugula salad, melt-in-your-mouth Emmental cheese (15%) and a special Caesar sauce!",
    type: "Chicken",
    starts: 4.7,
  },
  {
    id: 7,
    image: "https://mcdonalds.bg/wp-content/uploads/2023/02/BG_CSO_9052.png",
    name: "McNuggets™",
    price: "2.49",
    dis: "4 bites of chicken breast in golden, crispy breading with sauce of choice.",
    type: "Chicken",
    starts: 4.8,
  },
  {
    id: 8,
    image:
      "https://mcdonalds.bg/wp-content/uploads/2023/11/artboard-1_500x500.png",
    name: "Filet-o-Fish",
    price: "1.39",
    dis: "Warm bun, white fish fillet, Tartar sauce and Cheddar cheese (51%).",
    type: "Burgers & Sandwiches",
    starts: 4.6,
  },
  {
    id: 9,
    image: "https://mcdonalds.bg/wp-content/uploads/2023/01/BG_CSO_2145.png",
    name: "Chicken Wings",
    price: "5.49",
    dis: "5 pcs chicken wings in spicy crispy breading",
    type: "Chicken",
    starts: 4.8,
  },
  {
    id: 10,
    image: "https://mcdonalds.bg/wp-content/uploads/2023/01/BG_CSO_113.png",
    name: "Chicken Salad",
    price: "6.20",
    dis: "Crispy mix of fresh salads, fresh tomatoes, sweet corn, aromatic croutons, breaded chicken fillet and sauce of your choice",
    type: "Chicken",
    starts: 4.5,
  },
  {
    id: 11,
    image:
      "https://mcdonalds.bg/wp-content/uploads/2024/03/kamembert-500-x-500-3-broya-2.png",
    name: "Camembert Rings",
    price: "4.20",
    dis: " Crispy with a creamy center.",
    type: "Snacks & Slides",
    starts: 4.8,
  },
  {
    id: 12,
    image:
      "https://mcdonalds.bg/wp-content/uploads/2023/10/mcd_mcflavor_500x500.png",
    name: "McFlavor® Fries",
    price: "3.50",
    dis: "Medium fries with cheddar cheese (30%).",
    type: "Snacks & Slides",
    starts: 4.5,
  },
  {
    id: 13,
    image: "https://mcdonalds.bg/wp-content/uploads/2023/01/BG_CSO_3001.png",
    name: "French fries Small",
    price: "1.50",
    dis: "Golden freshly prepared french fries, 80 g",
    type: "Snacks & Slides",
    starts: 4.5,
  },
  {
    id: 14,
    image: "https://mcdonalds.bg/wp-content/uploads/2023/01/BG_CSO_3002.png",
    name: "French fries Regular",
    price: "2.50",
    dis: "Golden freshly prepared french fries, 114 g",
    type: "Snacks & Slides",
    starts: 4.8,
  },
  {
    id: 14,
    image: "https://mcdonalds.bg/wp-content/uploads/2023/01/BG_CSO_3003.png",
    name: "French fries Large",
    price: "3.50",
    dis: "Golden freshly prepared french fries, 150 g",
    type: "Snacks & Slides",
    starts: 4.6,
  },
  {
    id: 15,
    image: "https://mcdonalds.bg/wp-content/uploads/2023/01/BG_CSO_4002.png",
    name: "Coca-Cola",
    price: "1.20",
    type: "Beverages",
    starts: 4.6,
  },
  {
    id: 16,
    image: "https://mcdonalds.bg/wp-content/uploads/2023/01/Fanta.png",
    name: "Fanta",
    price: "1.10",
    type: "Beverages",
    starts: 4.7,
  },
];

export const categories = [
  "All",
  "Burgers & Sandwiches",
  "Beverages",
  "Chicken",
  "Snacks & Slides",
];
